default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gymgeniusapi_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: gymgeniusapi_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: gymgeniusapi_production
  username: gymgeniusapi
  password: <%= ENV["GYMGENIUSAPI_DATABASE_PASSWORD"] %>
